begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'solicitante' check (role in ('solicitante', 'tecnico', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.chamados (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  solicitante_nome text not null,
  solicitante_email text not null,
  unidade text not null,
  setor text not null,
  descricao text not null check (char_length(descricao) <= 500),
  prioridade text not null default 'normal' check (prioridade in ('normal', 'urgente')),
  status text not null default 'aberto' check (status in ('aberto', 'andamento', 'finalizado')),
  atendido_por text,
  solucao text check (char_length(solucao) <= 1000)
);

alter table public.chamados
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists solicitante_nome text,
  add column if not exists solicitante_email text,
  add column if not exists unidade text,
  add column if not exists setor text,
  add column if not exists descricao text,
  add column if not exists prioridade text,
  add column if not exists status text,
  add column if not exists atendido_por text,
  add column if not exists solucao text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'chamados'
      and column_name = 'nome'
  ) then
    execute '
      update public.chamados
      set solicitante_nome = coalesce(solicitante_nome, nome)
      where solicitante_nome is null
    ';
  end if;
end;
$$;

update public.chamados
set solicitante_nome = coalesce(solicitante_nome, 'Solicitante')
where solicitante_nome is null;

update public.chamados
set prioridade = lower(prioridade)
where prioridade is not null;

update public.chamados
set status = lower(status)
where status is not null;

alter table public.chamados
  alter column created_at set default now(),
  alter column user_id drop not null,
  alter column prioridade set default 'normal',
  alter column status set default 'aberto';

create index if not exists idx_chamados_user_id on public.chamados(user_id);
create index if not exists idx_chamados_status on public.chamados(status);

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid()
$$;

revoke all on function public.current_user_role() from public;
grant execute on function public.current_user_role() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'role', 'solicitante')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

insert into public.profiles (id, full_name, role)
select
  users.id,
  coalesce(users.raw_user_meta_data ->> 'full_name', split_part(users.email, '@', 1)),
  coalesce(users.raw_user_meta_data ->> 'role', 'solicitante')
from auth.users as users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.chamados enable row level security;

drop policy if exists profiles_select_self_or_support on public.profiles;
create policy profiles_select_self_or_support
on public.profiles
for select
to authenticated
using (
  id = auth.uid() or public.current_user_role() in ('tecnico', 'admin')
);

drop policy if exists chamados_insert_own on public.chamados;
create policy chamados_insert_own
on public.chamados
for insert
to authenticated
with check (
  user_id = auth.uid()
);

drop policy if exists chamados_select_own on public.chamados;
create policy chamados_select_own
on public.chamados
for select
to authenticated
using (
  user_id = auth.uid()
);

drop policy if exists chamados_select_support on public.chamados;
create policy chamados_select_support
on public.chamados
for select
to authenticated
using (
  public.current_user_role() in ('tecnico', 'admin')
);

drop policy if exists chamados_update_support on public.chamados;
create policy chamados_update_support
on public.chamados
for update
to authenticated
using (
  public.current_user_role() in ('tecnico', 'admin')
)
with check (
  public.current_user_role() in ('tecnico', 'admin')
);

commit;
